In [2]:
%matplotlib inline
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

from numpy import array
from sklearn.decomposition import PCA

In [27]:
# mergedf.to_csv("DB_CSV_merged_v1.csv")
mergedf = pd.read_csv('DB_CSV_merged_v1.csv', low_memory=False)

In [28]:
data = mergedf.iloc[:, -1035:-1]
# y_train = human_data_train["familyID"].values.reshape(-1, 1)

# y_test = dog_data_test["familyID"].values.reshape(-1, 1)
# X_test = dog_data_test.iloc[:, -1035:-1]
data.head()

k__Bacteria; p__Bacteroidetes; c__Flavobacteriia; o__Flavobacteriales; f__[Weeksellaceae]; g__Chryseobacterium; s__  \
0                                                  0                                                                     
1                                                  0                                                                     
2                                                  0                                                                     
3                                                  0                                                                     
4                                                  0                                                                     

   k__Bacteria; p__Actinobacteria; c__Actinobacteria; o__Actinomycetales; f__Nocardioidaceae; g__Nocardioides; s__  \
0                                                  0                                                                 
1                                                  0                                                                 
2                                                  0                                                                 
3                                                  0                                                                 
4                                                  0                                                                 

   k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__[Tissierellaceae]; g__Finegoldia; s__  \
0                                                  0                                                       
1                                                  0                                                       
2                                                  0                                                       
3                                                  0                                                       
4                                                  0                                                       

   k__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Rhodobacterales; f__Rhodobacteraceae; g__Rubellimicrobium; s__  \
0                                                  0                                                                           
1                                                  0                                                                           
2                                                  0                                                                           
3                                                  0                                                                           
4                                                  0                                                                           

   k__Bacteria; p__Actinobacteria; c__Actinobacteria; o__Actinomycetales; f__Nocardioidaceae; g__; s__  \
0                                                  0                                                     
1                                                  0                                                     
2                                                  0                                                     
3                                                  0                                                     
4                                                  0                                                     

   k__Bacteria; p__Firmicutes; c__Clostridia; o__Clostridiales; f__Lachnospiraceae; g__Roseburia; s__  \
0                                                  0                                                    
1                                                  0                                                    
2                                                  0                                                    
3                                                  0                                  

In [29]:
pca = PCA(3)

pca.fit(data)
print("PCA Components")
print(pca.components_)
print("--------")

print("PCA Explained Variance")
print(pca.explained_variance_)
print("--------")

print("PCA Transformed")
B = pca.transform(data)
print(B)

PCA Components
[[-2.01795468e-04 -1.37001355e-04 -6.81939767e-04 ... -1.41597550e-03
  -4.50290038e-03  2.69084770e-03]
 [-4.92814121e-04 -3.31550294e-04 -4.66326866e-03 ... -8.21552947e-03
  -2.84958307e-02  1.19309628e-03]
 [ 5.69427764e-05 -1.07705237e-04  1.78427030e-03 ...  7.32069526e-03
   2.75140859e-02  3.92815083e-04]]
--------
PCA Explained Variance
[2551.73218394  322.40202461  213.02131122]
--------
PCA Transformed
[[-22.8744285   32.71511655  13.45977029]
 [-31.26714638   9.39748115 -32.62611593]
 [-23.32746537  48.41322093  26.25094012]
 ...
 [-21.84370954   7.26654942  -5.38444321]
 [-33.15757572 -32.26766013  13.02405731]
 [-33.6381627   18.48363966 -37.23769164]]


In [30]:
PCA_df = pd.DataFrame(B, columns=["PCA1","PCA2","PCA3"])
PCA_df

PCA1       PCA2       PCA3
0     -22.874428  32.715117  13.459770
1     -31.267146   9.397481 -32.626116
2     -23.327465  48.413221  26.250940
3     -32.024744 -25.119389  10.547646
4     -31.587557  20.812031  -1.167072
5      45.257644  -7.557471   0.760815
6     -17.161460  -8.357726  -1.939940
7     -21.606513  36.934596  24.031603
8     -31.787674 -24.267267  11.423432
9     -31.896917   5.737169 -29.316454
10    -14.771126  18.170513   8.266155
11    -18.210024   1.624682   9.082937
12    -31.042662  41.343333  23.042090
13    -32.122016 -25.521388  10.869567
14    -32.101051  12.962826 -19.808163
15    130.145910  -3.937288  -1.557757
16    -18.148606  -5.866431  -1.806971
17    108.018837  -5.747051  -0.931766
18    -31.124001 -20.612504  11.599371
19    -32.065432   9.807054 -24.380556
20    -15.506778  -6.024178  -5.022157
21    -26.454297  -7.036983  -3.136594
22    -24.365342  -6.674559  -2.897224
23    -20.064962  -0.889320   1.094183
24    -30.497178 -14.238890   0.849258
25    -30.625871 -10.206749  -7.060485
26    141.818648  -3.789324  -1.942805
27     99.101963  -3.883968  -1.378293
28     30.118957  12.307401   3.537711
29    -28.559341  -9.887219   0.658983
...          ...        ...        ...
1020   64.267565  -2.539052  -1.817786
1021   63.458467  -1.458552   3.285077
1022  -29.457559  -9.333778  -0.006935
1023  -32.298625  11.504310 -24.941368
1024  -24.971720  -8.982976  -4.141231
1025   46.403487  -6.441467  -2.212794
1026   -6.569391  -9.309949  -2.941639
1027    0.935296 -15.194424   1.059456
1028  -31.915764 -22.820024   4.266864
1029  -30.383082 -10.449479  -5.615142
1030  -15.895102 -14.956462   2.165329
1031   -3.891838  -8.270543  -2.276146
1032  -29.255249  -7.973807  -3.671460
1033  -19.880246 -12.500353  -0.576958
1034  -31.230830 -18.295107   2.305755
1035  -29.936803  -8.513054  -4.885165
1036  136.075091  -3.869848  -2.084361
1037    0.451288  28.222397  16.735652
1038    4.212476  -8.297813  -6.260030
1039  -30.904611 -19.348787  10.405953
1040  -32.427473   8.355056 -33.712081
1041  -24.980717   4.420899   0.324423
1042  -15.761146  26.763868   9.709298
1043  -32.350409 -24.228276   5.870302
1044  -32.556559  16.378954 -20.360400
1045   49.501716  -4.113100  -3.730411
1046  -20.234775  46.545312  27.471421
1047  -21.843710   7.266549  -5.384443
1048  -33.157576 -32.267660  13.024057
1049  -33.638163  18.483640 -37.237692

[1050 rows x 3 columns]

In [31]:
import plotly.express as px
# df = px.data.iris()
fig = px.scatter_3d(PCA_df, x=PCA_df['PCA1'], y=PCA_df['PCA2'], z=PCA_df['PCA3']
                    ,
#                     color='sample_type', symbol='host_common_name', 
                    size_max=3, opacity=0.7)
# fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))
fig.show()

In [14]:
x = mergedf.iloc[:, -1035:-1]

In [ ]:
y = 

# Scaled Model Fitting

In [9]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
model = classifier.fit(X_train_scaled, y_train.ravel())

In [12]:
print(f'Test Data Model Score: {round(100*(classifier.score(X_test_scaled, y_test)),2)}%')
print("------------")
predictions = classifier.predict(X_test_scaled)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

Test Data Model Score: 16.38%
------------
First 10 Predictions:   ['family#71' 'family#71' 'family#71' 'family#3' 'family#71' 'family#64'
 'family#49' 'family#7' 'family#17' 'family#27']
First 10 Actual labels: [['family#3'], ['family#3'], ['family#3'], ['family#3'], ['family#3'], ['family#6'], ['family#6'], ['family#6'], ['family#6'], ['family#6']]


In [25]:
y_pred = model.predict(X_test_scaled)

outputdf = pd.DataFrame({"SampleName": dog_data_test["sample_name"],"Anonymized_Name":dog_data_test["anonymized_name"],"Prediction": y_pred, "Actual": y_test.ravel()}).reset_index(drop=True)
print(outputdf.shape)
outputdf.head()

(177, 4)


SampleName Anonymized_Name Prediction    Actual
0    797.03.CA.BackLeftPaw          FS_175  family#71  family#3
1   797.03.CA.BackRightPaw          FS_175  family#71  family#3
2       797.03.CA.Forehead          FS_175  family#71  family#3
3  797.03.CA.FrontRightPaw          FS_175   family#3  family#3
4         797.03.CA.Tongue          FS_175  family#71  family#3

In [26]:
sumOutput = outputdf.groupby(["Anonymized_Name","Actual","Prediction"]).count()
sumOutput.reset_index()
sumOutput.head()

SampleName
Anonymized_Name Actual   Prediction            
FS_175          family#3 family#3             1
                         family#71            4
FS_176          family#6 family#17            1
                         family#27            1
                         family#49            1

In [27]:
# sumOutput.groupby(["Anonymized_Name"])['SampleName'].max()
idx = sumOutput.groupby(["Anonymized_Name"])['SampleName'].transform(max) == sumOutput['SampleName']
maxOutput = sumOutput[idx]
maxOutput = maxOutput.reset_index()
print(maxOutput.shape)
# maxOutput

(72, 4)


In [28]:
maxOutput_noDup = maxOutput.drop_duplicates(subset=['Anonymized_Name'], keep="first")
print(maxOutput_noDup.shape)
# maxOutput_noDup

(36, 4)


In [29]:
maxOutput_C = maxOutput_noDup[maxOutput_noDup.Actual == maxOutput_noDup.Prediction]

print(maxOutput_C.shape)
# maxOutput_C

(8, 4)


In [30]:
maxOutput_I = maxOutput_noDup[maxOutput_noDup.Actual != maxOutput_noDup.Prediction]

print(maxOutput_I.shape)
# maxOutput_I

(28, 4)


In [31]:
correct_total = maxOutput_C["Anonymized_Name"].count()
incorrect_total = maxOutput_I["Anonymized_Name"].count()

accuracy_maxed_pred = correct_total/(correct_total + incorrect_total)
print(f' Accuracy of most-predicted (dog) family: {round(accuracy_maxed_pred,3)}')

 Accuracy of most-predicted (dog) family: 0.222
